---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
- name: Pre install config for ironic
  hosts: localhost
  tasks:
    - name: Define networks for ironic to use
      config_template:
        src: "../../openstack-ansible/etc/openstack_deploy/openstack_user_config.yml.aio"
        dest: "../../openstack-ansible/etc/openstack_deploy/openstack_user_config.yml.aio"
        owner: "root"
        group: "root"
        mode: "0644"
        config_overrides: "{{ cidr_networks_ironic }}"
        config_type: "yaml"

    - name: Add IPs to used_ips list
      config_template:
        src: "../../openstack-ansible/etc/openstack_deploy/openstack_user_config.yml.aio"
        dest: "../../openstack-ansible/etc/openstack_deploy/openstack_user_config.yml.aio"
        owner: "root"
        group: "root"
        mode: "0644"
        config_overrides: "{{ used_ips }}"
        config_type: "yaml"

    - name: Setup global overrides
      config_template:
        src: "../../openstack-ansible/etc/openstack_deploy/openstack_user_config.yml.aio"
        dest: "../../openstack-ansible/etc/openstack_deploy/openstack_user_config.yml.aio"
        owner: "root"
        group: "root"
        mode: "0644"
        config_overrides: "{{ ironic_networks }}"
        config_type: "yaml"

    - name: Define group hosts
      config_template:
        src: "../../openstack-ansible/etc/openstack_deploy/openstack_user_config.yml.aio"
        dest: "../../openstack-ansible/etc/openstack_deploy/openstack_user_config.yml.aio"
        owner: "root"
        group: "root"
        mode: "0644"
        config_overrides: "{{ group_hosts_ironic }}"
        config_type: "yaml"

    - name: Setup endpoints for swift/ironic health checks
      config_template:
       src: "../etc/openstack_deploy/user_osa_variables_overrides.yml"
       dest: "../etc/openstack_deploy/user_osa_variables_overrides.yml"
       owner: "root"
       group: "root"
       mode: "0644"
       config_overrides: "{{ ironic_endpoint_config }}"
       config_type: "yaml"

    - name: Configure neutron DHCP to be non-authorative
      config_template:
        src: "../etc/openstack_deploy/user_osa_variables_overrides.yml"
        dest: "../etc/openstack_deploy/user_osa_variables_overrides.yml"
        owner: "root"
        group: "root"
        mode: "0644"
        config_overrides: "{{ ironic_neutron_dhcp_config }}"
        config_type: "yaml"

  vars:
    cidr_networks_ironic:
      cidr_networks:
           tftp: "172.29.232.0/22"
           ironic-ipmi: "172.29.228.0/22"
    ironic_networks:
      global_networks:
        provider_networks:
          - network:
            container_bridge: "br-ironic-ipmi"
            container_type: "veth"
            container_interface: "eth_ipmi"
            ip_from_q: "ironic-ipmi"
            type: "raw"
            group_binds:
            - ironic-infra_hosts
          - network:
            container_bridge: "br-tftp"
            container_type: "veth"
            container_interface: "eth_tftp"
            ip_from_q: "ironic-ipmi"
            type: "flat"
            net_name: "tftp"
            ip_from_q: "tftp"
            group_binds:
            - neutron_linuxbridge_agent
            - ironic_all
    group_hosts_ironic:
      ironic-compute_hosts:
        infra01:
          ip: "172.29.236.100"
      ironic-infra_hosts:
        infra01:
          ip: "172.29.236.100"
    ironic_endpoint_config:
      extra_lb_vip_addresses:
        - "{{ ansible_eth0.ipv4.address }}"
      ironic_openstack_api_url: "{{ ansible_eth0.ipv4.address }}:{{ ironic_service_port }}"
      ironic_swift_endpoint: "{{ ansible_eth0.ipv4.address }}:8080"
    ironic_neutron_dhcp_config:
      neutron_dhcp_config:
        dhcp-option-force: "26,1500"
        dhcp-ignore: "tag:!known"
        log-facility: "/var/log/neutron/dnsmasq.log"
    used_ips:
      used_ips:
        - "172.29.232.1,172.29.232.50"
        - "172.29.228.1,172.29.228.50"
